[damian-channel-strip]
name = "Damian Channel Strip"

[flattery]
name = "Flattery"

[tape_stop]
name = "Tape Stop"

[openwurli-ui]
name = "OpenWurli UI"

[chordboard]
name = "Chordboard"

[fundament]
name = "Fundament"
