[package]
name = "pleasant-ui"
version = "0.1.0"
edition = "2021"
authors = ["Fergler"]
license = "GPL-3.0-or-later"
description = "Pleasant UI theme, canvas drawing, and interactive components for nih-plug"

[dependencies]
pleasant-dsp = { path = "../pleasant-dsp" }
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git" }
nih_plug_vizia = { git = "https://github.com/robbert-vdh/nih-plug.git" }
atomic_float = "1"
dark-light = "3"
