use serde_json::{json,Value};
use std::{hint::black_box,time::Instant};
macro_rules! dispatch {($s:expr,$e:ident,$body:expr)=>{match $s{Engine::Reference($e)=>$body,Engine::Candidate($e)=>$body}};}
enum Engine{Reference(recovery_reference::WurliEngine),Candidate(recovery_candidate::WurliEngine)}
#[derive(Clone,Copy)]
enum Event{On(u8,f32),Off(u8),Sustain(bool),Depth(f64),Decay(f64),Hardness(f64),Pickup(f64),Response(f64),Volume(f64),Speaker(f64),Rail(bool),Reset,Rate(f64),Toggle}
impl Engine{
 fn new(candidate:bool,rate:f64,heavy:bool,mlp:bool,depth:f64)->Self{
  let mut e=if candidate{use recovery_candidate::{WurliEngine,CircuitMode};Engine::Candidate(WurliEngine::new_with_circuit_mode(rate,if heavy{CircuitMode::Heavy}else{CircuitMode::Fast}))}else{use recovery_reference::{WurliEngine,CircuitMode};Engine::Reference(WurliEngine::new_with_circuit_mode(rate,if heavy{CircuitMode::Heavy}else{CircuitMode::Fast}))};
  dispatch!(&mut e,x,{x.ensure_buffer_capacity(1024);x.set_noise_enabled(false);x.set_mlp_enabled(mlp);x.set_tremolo_depth(depth);x.warm_up();});e
 }
 fn event(&mut self,event:Event){
  if matches!(event,Event::Toggle){match self{Engine::Reference(e)=>{use recovery_reference::CircuitMode as M;e.set_circuit_mode(if e.circuit_mode()==M::Fast{M::Heavy}else{M::Fast});},Engine::Candidate(e)=>{use recovery_candidate::CircuitMode as M;e.set_circuit_mode(if e.circuit_mode()==M::Fast{M::Heavy}else{M::Fast});}}return;}
  dispatch!(self,e,match event{Event::On(n,v)=>e.note_on_extended(n,v),Event::Off(n)=>e.note_off_extended(n),Event::Sustain(v)=>e.set_sustain(v),Event::Depth(v)=>e.set_tremolo_depth(v),Event::Decay(v)=>e.set_reed_decay(v),Event::Hardness(v)=>e.set_hammer_hardness(v),Event::Pickup(v)=>e.set_pickup_drive(v),Event::Response(v)=>e.set_tremolo_response(v),Event::Volume(v)=>e.set_volume(v),Event::Speaker(v)=>e.set_speaker_character(v),Event::Rail(v)=>e.set_rail_sag(v),Event::Reset=>e.reset(),Event::Rate(v)=>e.set_sample_rate(v),Event::Toggle=>unreachable!()});
 }
 fn render(&mut self,b:&mut[f32]){dispatch!(self,e,e.render(b));}
 fn lifetime(&self)->Option<[u64;5]>{match self{Engine::Reference(_)=>None,Engine::Candidate(e)=>{let d=e.heavy_solver_diagnostics();Some([d.primary_failures,d.skipped_recoveries,d.recovery_attempts,d.guard_resets,d.last_iteration_rejections])}}}
 fn summary(&self)->Value{dispatch!(self,e,{let d=e.power_amp_diag();json!({"nan":e.nan_guard_fires(),"amp_clamp":d.0,"amp_maxiter":d.1,"peak_bits":d.2.to_bits(),"active":e.active_voice_count(),"held":e.held_voice_count(),"sustained":e.sustained_voice_count(),"sustain":e.is_sustain_held()})})}
}
#[derive(Clone)]
struct Case{name:String,rate:u32,heavy:bool,mlp:bool,block:usize,depth:f64,len:usize,events:Vec<(usize,Event)>}
fn chord(n:usize)->Vec<u8>{if n<=6{[48,55,60,63,67,70][..n].to_vec()}else{(0..n).map(|i|33+i as u8).collect()}}
fn on(events:&mut Vec<(usize,Event)>,at:usize,notes:&[u8],v:f32){for &n in notes{events.push((at,Event::On(n,v)));}}
fn off(events:&mut Vec<(usize,Event)>,at:usize,notes:&[u8]){for &n in notes{events.push((at,Event::Off(n)));}}
fn cases()->Vec<Case>{let mut out=vec![];
 for n in [6,64]{let mut ev=vec![];on(&mut ev,0,&chord(n),0.95);out.push(Case{name:format!("prior-review-heavy{n}"),rate:48000,heavy:true,mlp:false,block:256,depth:0.5,len:24128,events:ev});}
 for rate in [44100,48000,88200,96000]{for heavy in [false,true]{for mlp in [false,true]{let stem=format!("{rate}-{}-mlp{mlp}",if heavy{"heavy"}else{"fast"});
  for (index,n) in [6,64].into_iter().enumerate(){let mut ev=vec![(0,Event::Decay(20.0))];let notes=chord(n);on(&mut ev,0,&notes,0.95);ev.push((4096,Event::Depth(0.0)));ev.push((8192,Event::Depth(1.0)));out.push(Case{name:format!("{stem}-held{n}"),rate,heavy,mlp,block:[64,257][index],depth:0.5,len:12288,events:ev});}
  let mut ev=vec![(0,Event::Decay(20.0)),(0,Event::Sustain(true))];
  // All 128 extended MIDI notes, varied exact f32 velocities; second bank steals voices.
  for n in 0u8..=127{ev.push(((n as usize/16)*512,Event::On(n,match n%4{0=>0.001,1=>0.25,2=>0.95,_=>1.0})));if n>=16{ev.push(((n as usize/16)*512+256,Event::Off(n-16)));}}
  for n in 0u8..=127{ev.push((4352,Event::Off(n)));}ev.push((4608,Event::Sustain(false)));
  ev.push((5120,Event::Hardness(2.0)));ev.push((5120,Event::Pickup(2.0)));ev.push((5120,Event::Volume(1.0)));ev.push((5120,Event::Speaker(1.0)));ev.push((5120,Event::Response(0.5)));on(&mut ev,5376,&chord(6),1.0);off(&mut ev,6144,&chord(6));ev.push((6400,Event::Rail(false)));ev.push((7168,Event::Rail(true)));ev.sort_by_key(|x|x.0);
  out.push(Case{name:format!("{stem}-extended-lifecycle-controls"),rate,heavy,mlp,block:if rate==44100&&!mlp{1}else{1024},depth:0.5,len:12288,events:ev});
 }}}
 for heavy in [false,true]{let mut ev=vec![];on(&mut ev,0,&chord(6),0.95);ev.push((2048,Event::Toggle));ev.push((2560,Event::Toggle));ev.push((3072,Event::Toggle));ev.push((10000,Event::Toggle));ev.push((14900,Event::Toggle));ev.push((15000,Event::Toggle));ev.push((17000,Event::Rate(96000.0)));ev.push((20000,Event::Toggle));ev.push((32000,Event::Reset));on(&mut ev,32000,&[0,21,60,92,127],1.0);ev.push((35000,Event::Rate(44100.0)));ev.push((38000,Event::Toggle));ev.push((45000,Event::Rate(88200.0)));off(&mut ev,48000,&[0,21,60,92,127]);out.push(Case{name:format!("mode-rate-reset-{}",if heavy{"heavy"}else{"fast"}),rate:48000,heavy,mlp:true,block:257,depth:0.5,len:60000,events:ev});}
 // Focused long tail: released/sustained no-damper upper notes under 20x decay.
 let mut ev=vec![(0,Event::Decay(20.0)),(0,Event::Sustain(true))];on(&mut ev,0,&[0,21,48,60,91,92,108,127],0.95);off(&mut ev,4800,&[0,21,48,60,91,92,108,127]);ev.push((9600,Event::Sustain(false)));ev.push((120000,Event::Depth(0.0)));ev.push((180000,Event::Depth(1.0)));
 out.push(Case{name:"long-tail-heavy-20x-5seconds".into(),rate:48000,heavy:true,mlp:true,block:1024,depth:0.5,len:240000,events:ev});out
}
fn audio(shortcut:bool)->Value{let mut rows=vec![];let mut total=0u64;let mut all=true;
 for c in cases(){if std::env::var("RECOVERY_CASE_FILTER").is_ok_and(|filter|!filter.split(",").any(|part|c.name.contains(part))){continue;}let mut a=Engine::new(false,c.rate as f64,c.heavy,c.mlp,c.depth);let mut b=Engine::new(true,c.rate as f64,c.heavy,c.mlp,c.depth);let(mut pos,mut ei,mut mismatch,mut diag_mismatch,mut nonfinite,mut hash)=(0usize,0usize,0u64,0u64,0u64,0u64);let mut first=None;let mut counter_prev=b.lifetime().unwrap();let mut counter_totals=counter_prev;let mut counter_invariant=true;let mut ab=vec![0f32;c.block];let mut bb=ab.clone();
  while pos<c.len{while ei<c.events.len()&&c.events[ei].0==pos{let event=c.events[ei].1;a.event(event);b.event(event);if matches!(event,Event::Rate(_)){let now=b.lifetime().unwrap();for i in 0..5{counter_totals[i]+=now[i];}counter_prev=now;}ei+=1;}let next=if ei<c.events.len(){c.events[ei].0}else{c.len};let n=c.block.min(c.len-pos).min(next-pos);assert!(n>0);a.render(&mut ab[..n]);b.render(&mut bb[..n]);for (i,(&x,&y))in ab[..n].iter().zip(&bb[..n]).enumerate(){if x.to_bits()!=y.to_bits(){mismatch+=1;if first.is_none(){first=Some(json!({"sample":pos+i,"reference_bits":x.to_bits(),"candidate_bits":y.to_bits()}));}}nonfinite+=u64::from(!x.is_finite()||!y.is_finite());hash=hash.wrapping_mul(16777619)^x.to_bits() as u64;}if a.summary()!=b.summary(){diag_mismatch+=1;}let now=b.lifetime().unwrap();counter_invariant&=(if shortcut{now[0]==now[1]&&now[2]==0}else{now[1]==0&&now[0]==now[2]})&&now[3]>=now[0]+now[4];for i in 0..5{counter_totals[i]+=if now[i]>=counter_prev[i]{now[i]-counter_prev[i]}else{now[i]};}counter_prev=now;pos+=n;}
  let ok=mismatch==0&&diag_mismatch==0&&nonfinite==0&&counter_invariant;all&=ok;total+=c.len as u64;let row=json!({"name":c.name,"rate":c.rate,"heavy":c.heavy,"mlp":c.mlp,"block":c.block,"samples":c.len,"different_bits":mismatch,"diagnostic_mismatch_callbacks":diag_mismatch,"nonfinite":nonfinite,"candidate_lifetime_totals":counter_totals,"counter_fields":["primary_failures","skipped_recoveries","recovery_attempts","guard_resets","last_iteration_rejections"],"counter_invariant":counter_invariant,"reference_hash":hash,"first_difference":first,"reference_final":a.summary(),"candidate_final":b.summary()});println!("{}: {} ({} samples)",c.name,if ok{"EXACT"}else{"FAIL"},c.len);rows.push(row);
 }
 let skipped:u64=rows.iter().map(|r|r["candidate_lifetime_totals"][1].as_u64().unwrap()).sum();let final_iter:u64=rows.iter().map(|r|r["candidate_lifetime_totals"][4].as_u64().unwrap()).sum();let primary:u64=rows.iter().map(|r|r["candidate_lifetime_totals"][0].as_u64().unwrap()).sum();json!({"all_exact":all&&primary>0&&(!shortcut||skipped>0),"shortcut_expected":shortcut,"observed_primary_failures":primary,"observed_last_iteration_rejections":final_iter,"observed_skipped_recoveries":skipped,"total_samples":total,"cases":rows,"limits":"Full f32 output bits and public guard/voice summaries at every callback. Final private circuit state is not directly observed; subsequent trajectory, rate reset and switches exercise restoration."})
}
fn quantile(v:&mut[f64],q:f64)->f64{v.sort_by(f64::total_cmp);v[((v.len()-1) as f64*q)as usize]}
fn trial(candidate:bool,heavy:bool,n:usize,depth:f64,block:usize,len:usize)->Value{let mut e=Engine::new(candidate,48000.0,heavy,false,depth);let mut buf=vec![0.0;block];let t=Instant::now();for note in chord(n){e.event(Event::On(note,0.95));}let event_ns=t.elapsed().as_nanos();let mut cost=0f64;let mut blocks=vec![];let mut done=0;let mut hash=0u64;
 while done<len{let size=block.min(len-done);let t=Instant::now();e.render(black_box(&mut buf[..size]));let ns=t.elapsed().as_secs_f64()*1e9;cost+=ns;blocks.push(ns/1000.0);for &s in &buf[..size]{hash=hash.wrapping_mul(16777619)^s.to_bits()as u64;}done+=size;}
 let p99=quantile(&mut blocks,0.99);json!({"render_ns_per_sample":cost/len as f64,"p99_block_us":p99,"max_block_us":blocks.last(),"note_on_total_ns":event_ns,"blocks":blocks.len(),"hash":hash,"candidate_lifetime_final":e.lifetime(),"final":e.summary()})
}
fn cpu(repeats:usize)->Value{let mut rows=vec![];let mut configs=vec![];for n in [1,6,32,64]{for depth in [0.0,0.5]{configs.push((true,n,depth,256,24128));}}for n in [6,64]{configs.push((false,n,0.5,256,24128));}for block in [1,64,257,1024]{configs.push((true,6,0.5,block,8192));}
 for (heavy,n,depth,block,len)in configs{let mut pairs=vec![];let mut pairs_exact=true;let mut baseline=vec![];let mut candidate=vec![];let mut ratios=vec![];for i in 0..repeats{let(a,b)=if i%2==0{let a=trial(false,heavy,n,depth,block,len);let b=trial(true,heavy,n,depth,block,len);(a,b)}else{let b=trial(true,heavy,n,depth,block,len);let a=trial(false,heavy,n,depth,block,len);(a,b)};pairs_exact&=a["hash"]==b["hash"]&&a["final"]==b["final"];let x=a["render_ns_per_sample"].as_f64().unwrap();let y=b["render_ns_per_sample"].as_f64().unwrap();baseline.push(x);candidate.push(y);ratios.push(y/x);pairs.push(json!({"order":if i%2==0{"reference,candidate"}else{"candidate,reference"},"reference":a,"candidate":b}));}
 let med_a=quantile(&mut baseline,0.5);let med_b=quantile(&mut candidate,0.5);let ratio=quantile(&mut ratios,0.5);let row=json!({"heavy":heavy,"voices":n,"depth":depth,"block":block,"samples_per_trial":len,"repeats":repeats,"paired_hashes_and_public_state_exact":pairs_exact,"reference_median_ns_per_sample":med_a,"candidate_median_ns_per_sample":med_b,"paired_median_reduction_percent":100.0*(1.0-ratio),"pairs":pairs});println!("{} voices {n} depth {depth} block {block}: {med_a:.2} -> {med_b:.2} ns/sample ({:.2}% paired reduction)",if heavy{"Heavy"}else{"Fast"},100.0*(1.0-ratio));rows.push(row);}
 json!({"conditions":"48k, MLP/hiss off, volume0.5, speaker0, native rails, exact0.95 velocity, 0.6s warmup excluded. Alternating pair order, isolated sequential trials. Callback render only; separate note event timing. Short-run wall-clock evidence, not DAW meters.","rows":rows})
}
fn main(){let args:Vec<_>=std::env::args().collect();let mode=args.get(1).map(String::as_str).unwrap_or("audio");let output=args.get(2).expect("output JSON path required");let result=match mode{"audio"=>audio(true),"audio-full"=>audio(false),"cpu"=>cpu(args.get(3).and_then(|s|s.parse().ok()).unwrap_or(5)),_=>panic!("use audio or cpu")};std::fs::write(output,serde_json::to_string_pretty(&result).unwrap()+"\n").unwrap();if mode.starts_with("audio")&&!result["all_exact"].as_bool().unwrap(){std::process::exit(1);}}
