[package]
name = "openwurli-ui"
version = "0.1.0"
edition = "2021"
authors = ["Fergler"]
license = "GPL-3.0-or-later"
description = "Pleasant UI wrapper for the OpenWurli electric piano"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git" }
nih_plug_vizia = { git = "https://github.com/robbert-vdh/nih-plug.git" }
pleasant-ui = { path = "../pleasant-ui" }
openwurli-dsp = { git = "https://github.com/Ferglerz/openwurli.git", rev = "fd4f603dd8deef7a57d4449826f2c9d5dd53757e" }
