[package]
name = "scd-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
scd-core = { path = "../scd-core" }
nih_plug = { path = "../../vendor/nih-plug" }
nih_plug_vizia = { path = "../../vendor/nih-plug/nih_plug_vizia" }
pleasant-ui = { path = "../../../audio-plugins/pleasant-ui" }
atomic_float = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
